config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :baskets, only: [:index, :show, :create, :new] do
    resources :orders, only: [:create, :new]
    resources :reviews, only: [ :new, :create ]
    resources :favourites, only: [:new, :create]
   end

  get 'favourites', to: 'baskets#favourites'
  resources :favourites, only: [:destroy]

  resources :orders, only: [:index] do
    member do
      get :accept
      get :decline
      get :cancel
    end
  end
  # get 'orders/:order_id/accept', to: 'orders#accept', as: :accept
  # get 'orders/:order_id/decline', to: 'orders#decline', as: :decline
  # get 'orders/:order_id/cancel', to: 'orders#cancel', as: :cancel
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :description, :address, :price, presence: true
  validates :status, inclusion: { in: %w[available reserved unavailable] }
  has_one_attached :photo


end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :basket

  validates :basket, uniqueness: { scope: :user}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :basket
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :basket
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites

  ROLES = %w[Restaurant Consumer]
  validates :role, inclusion: { in: ROLES }

  def restaurant?
    role == 'Restaurant'
  end

  def consumer?
    role == 'Consumer'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:role, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:role, :email, :password, :current_password)}
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if user_signed_in? && current_user.restaurant?
      @baskets = policy_scope(Basket).where("user_id = #{current_user.id}")

    end
    if !user_signed_in? || current_user.consumer?
      @baskets = policy_scope(Basket).order(created_at: :desc)
    end
    # raise
  end

  def show
    @basket = Basket.find(params[:id])
    authorize @basket

    @basket.geocode

    @markers = [{
        lat: @basket.latitude,
        lng: @basket.longitude
      }]

  end

  def new
    @basket = Basket.new()
    authorize @basket
  end

  def create
    @basket = Basket.new(basket_params)
    @basket.original_stock = @basket.stock
    authorize @basket
    # IF USER IS LOGGED IN
    @basket.user_id = current_user.id
    if @basket.save
      redirect_to baskets_path
    else
      render :new
    end
  end

  def favourites
    @favourite_baskets = []

    current_user.favourites.each do |favourite|
      basket = Basket.find(favourite.basket_id)
      authorize basket
      @favourite_baskets << basket
    end

  end

  private

  def basket_params
    params.require(:basket).permit(:description, :address, :price, :stock, :photo, :name)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  # def new
  #   @basket = Basket.find(params[:basket_id])
  #   @favourite = Favourite.new
  #   authorize @favourite
  #   # raise
  #   create
  #   redirect_to baskets_path
  # end

  def create
    @user = current_user
    @basket = Basket.find(params[:basket_id])
    @favourite = Favourite.new(user: @user, basket: @basket)
    authorize @favourite
    @favourite.save
    redirect_to baskets_path
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    authorize @favourite
    @favourite.destroy
    redirect_to baskets_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = policy_scope(Order).where("user_id = #{current_user.id}")
    @baskets = policy_scope(Basket).where("user_id = #{current_user.id}")
  end

  def new
    @basket = Basket.find(params[:basket_id])
    @order = Order.new
    authorize @order
    create
  end

  def create
    basket = Basket.find(params[:basket_id])
    @order = Order.new
    authorize @order
    @order.price = basket.price
    @order.status = 'requested'
    @order.basket_id = basket.id
    @order.user_id = current_user.id
    if @order.save
      basket.status = 'reserved'
      basket.save
    end
    redirect_to orders_path
  end

  def decline
    @order = Order.find(params[:id])
    @order.status = 'Declined'
    @order.save
    basket = @order.basket
    basket.status = 'available'
    authorize basket
    basket.save
    redirect_to orders_path
  end

  def accept
    @order = Order.find(params[:id])
    @order.status = 'Confirmed'
    @order.save
    basket = @order.basket
    basket.stock -= @order.quantity
    authorize @order
    if basket.stock <= 0
      basket.status = 'unavailable'
    else
      basket.status = 'available'
    end
    basket.save

    redirect_to orders_path
  end

  def cancel
    @order = Order.find(params[:id])
    @order.status = 'Cancelled'
    @order.save
    basket = @order.basket
    basket.stock += 1
    if basket.stock <= 0
      basket.status = 'unavailable'
    else
      basket.status = 'available'
    end
    authorize @order
    basket.save
    redirect_to orders_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @basket = Basket.find(params[:basket_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @basket = Basket.find(params[:basket_id])
    @review.basket = @basket
    if @review.save
      redirect_to basket_path(@basket)
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/baskets/favourites.html.erb
  <% basket_array = %w[
https://images.unsplash.com/photo-1458672584924-ed089c687402?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80

https://images.unsplash.com/photo-1616109748085-7b89c0807927?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80

https://images.unsplash.com/photo-1484848560771-c55afee65e0f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80

https://images.unsplash.com/photo-1592455552754-22c10b36b452?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTd8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1588608468762-3b7843a5d5fb?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTV8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1600626333392-59a20e646d97?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzB8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1512578101635-3d8804b016c2?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzJ8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1510442515885-9a9c05e77b79?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njh8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1508431822127-707daa5c7f21?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTZ8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1565809655810-3973da946da1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80
]%>

<div class="container">
<% if @favourite_baskets.size > 0  %>
  <h2 class="text-center mt-4">My saved baskets</h2>
      <div class="container pt-3">
    <div class="row">
      <% @favourite_baskets.each do |basket| %>
        <div class="col-md-12 col-sm-12 col-xl-6">
          <div class="basket-card">
            <div class="wrapper">
              <div class="product-img">
                <% if basket.photo.attached? %>
                  <%= cl_image_tag basket.photo.key, height: 321, width: 250, crop: :fill %>
                <% else%>
                  <img src="<%=basket_array.sample%>" height="321" width="250">
                <%end%>
              </div>
              <div class="bookmark-heart">
              <%= link_to basket_favourites_url(basket), remote: true do %>
                <i class='fas fa-heart align-self-center text-center '></i>
              <% end %>
              </div>
              <div class="product-info">
                <div class="product-text">
                <% if basket.name == '' || basket.name.include?('Faker') %>
                  <h1>Basket #<%=basket.id%></h1>
                <% else %>
                  <h1><%= basket.name %></h1>
                <% end %>
                  <h2>by <%= User.find(basket.user_id).email.split('@').first %></h2>
                  <p><%=basket.description%> </p>
                </div>
                <div class="price-flex">
                  <p><%= basket.price %> R$</p>
                  <div class="product-price-btn">
                    <% if user_signed_in? && current_user.restaurant?%>
                      <%= link_to basket_url(basket) do  %>
                      <button type="button">details</button>
                      <% end  %>
                    <% else %>
                      <%= link_to basket_url(basket) do  %>
                      <button type="button">details</button>
                      <% end  %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>

<% else %>
  <h2>You don't have any saved baskets yet </h2>
<% end %>
</div>

app/views/baskets/index.html.erb
<div class="all-baskets">

  <% if user_signed_in? && current_user.restaurant? %>
    <div class="container">
      <br>
      <% if @baskets.size == 0 %>
        <h1 class="text-center"> You dont have any published baskets yet!</h1>
        <div class="container text-center">
          <%= link_to new_basket_url() do  %>
            <button class="btn-sign mb-1 mt-3 rounded-3 text-center" id='add-basket-button'>Add a basket!</button>
          <% end %>
        </div>

      <% else %>
      <div class="container text-center">
        <%= link_to new_basket_path do  %>
            <button class="btn-sign mb-1 mt-3 rounded-3" id='add-basket-button'>Add a new Basket!</button>
          <% end %>
          <h1 class="text-center"> Check your published baskets</h1>
      </div>

      <% end %>
    </div>
  <% end %>

  <% basket_array = %w[
https://images.unsplash.com/photo-1458672584924-ed089c687402?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80

https://images.unsplash.com/photo-1616109748085-7b89c0807927?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80

https://images.unsplash.com/photo-1484848560771-c55afee65e0f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80

https://images.unsplash.com/photo-1592455552754-22c10b36b452?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTd8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1588608468762-3b7843a5d5fb?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTV8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1600626333392-59a20e646d97?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzB8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1512578101635-3d8804b016c2?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzJ8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1510442515885-9a9c05e77b79?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njh8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1508431822127-707daa5c7f21?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTZ8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1565809655810-3973da946da1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80
]%>

  <div class="container pt-3">
    <div class="row">
      <% @baskets.each do |basket| %>
        <div class="col-md-12 col-sm-12 col-xl-6">
          <div class="basket-card">
            <div class="wrapper">
              <div class="product-img">
                <% if basket.photo.attached? %>
                  <%= cl_image_tag basket.photo.key, height: 321, width: 250, crop: :fill %>
                <% else%>
                  <img src="<%=basket_array.sample%>" height="321" width="250">
                <%end%>
              </div>
              <div class="bookmark-heart">
              <% if favourite = Favourite.find_by(user: current_user, basket: basket)  %>
                  <%= link_to favourite_path(favourite), method: :delete, remote: true  do %>
                    <i class='fas fa-heart align-self-center text-center '></i>
                  <% end %>
              <% else %>
                  <%= link_to basket_favourites_url(basket),method: :post, remote: true do %>
                    <i class='far fa-heart align-self-center text-center '></i>
                  <% end %>
              <%end%>
              </div>
              <div class="product-info">
                <div class="product-text">
                <% if basket.name == '' || basket.name.include?('Faker') %>
                  <h1>Basket #<%=basket.id%></h1>
                <% else %>
                  <h1><%= basket.name %></h1>
                <% end %>
                  <h2>by <%= User.find(basket.user_id).email.split('@').first %></h2>
                  <p><%=basket.description%> </p>
                </div>
                <div class="price-flex">
                  <p><%= basket.price %> R$</p>
                  <div class="product-price-btn">
                    <% if user_signed_in? && current_user.restaurant?%>
                      <%= link_to basket_url(basket) do  %>
                      <button type="button">details</button>
                      <% end  %>
                    <% else %>
                      <%= link_to basket_url(basket) do  %>
                      <button type="button">details</button>
                      <% end  %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
  <% basket_array = %w[
https://images.unsplash.com/photo-1458672584924-ed089c687402?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80

https://images.unsplash.com/photo-1616109748085-7b89c0807927?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80

https://images.unsplash.com/photo-1484848560771-c55afee65e0f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80

https://images.unsplash.com/photo-1592455552754-22c10b36b452?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTd8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1588608468762-3b7843a5d5fb?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OTV8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1600626333392-59a20e646d97?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzB8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1512578101635-3d8804b016c2?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzJ8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1510442515885-9a9c05e77b79?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njh8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1508431822127-707daa5c7f21?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTZ8fGZvb2QlMjBiYXNrZXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60

https://images.unsplash.com/photo-1565809655810-3973da946da1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80
]%>


<div class="dashboard-container">

<% if current_user.consumer? %>
  <div class="orders">
    <h1>My Green Orders</h1>
    <% if @orders.count == 0 %>
      <p>You don't have any order yet...</p>
      <div class="container text-center">
        <%= link_to baskets_path, class: 'btngui', :action => 'go' do %>
          <button>Check out the available baskets!</button>
        <% end%>
      </div>
    <% else %>
    <div class="filter-buttons">

      <button class="btngui" id="request-btn" data-toggle="button" aria-pressed="true" autocomplete="off"> Requested</button>
      <button class="btngui" id="confirm-btn" data-toggle="button" aria-pressed="true" autocomplete="off"> Confirmed</button>
      <button class="btngui" id="cancel-btn" data-toggle="button" aria-pressed="true" autocomplete="off"> Cancelled</button>
    </div>

      <div class="orders-flex-box">
          <% @orders.each do |order| %>
            <div class="orders-card <%= order.status.capitalize %>">
              <div class="card-content">
                <div class="image-order">
                  <% if order.basket.photo.attached? %>
                    <%= cl_image_tag order.basket.photo.key, height: 150, width: 200, crop: :fill %>
                  <% else%>
                    <img src="<%= basket_array.sample%>" height="150" width="200">
                  <%end%>
                </div>
                <h2><%= order.basket.name %></h2>
                <p>R$ <%= order.price %></p>

                <p><strong><%= order.status.capitalize %></strong></p>
              </div>
            </div>
          <% end %>
      </div>
    <% end %>
  </div>


<% else%>
  <div class="baskets">
    <h2>My Baskets</h2>
    <% if @baskets.count == 0 %>
      <p>You don't have any published baskets yet.</p>
      <div class="container text-center">
        <%= link_to new_basket_path, class: 'btngui', :action => 'go' do %>
          <button>Publish a new basket!</button>
        <% end%>
      </div>
    <% else %>
      <div class="filter-buttons">
        <button class="btn btn-outline-primary" id="reserved-btn" data-toggle="button" aria-pressed="true" autocomplete="off"> Reserved</button>
        <button class="btn btn-outline-primary" id="available-btn" data-toggle="button" aria-pressed="true" autocomplete="off"> Available</button>
      </div>
    <div class="orders-flex-box">
      <% @baskets.each do |basket| %>
        <div class="basket-card-db <%= basket.status.capitalize %>">
          <div class="card-content">
            <h2><%= basket.name %></h2>
            <p>R$ <%= basket.price %></p>
            <p>Stock: <%= basket.stock %></p>
            <p><strong><%= basket.status.capitalize %></strong></p>
              <button class="btn btn-block btn-outline-primary show-orders-button" data-toggle="button" data-basketId ='<%=basket.id%>' aria-pressed="false" autocomplete="off"><strong><%=basket.orders.count%></strong> orders</button>
            <div class="basket-orders">
                <% basket.orders.each do |order| %>
                  <div class="basket-orders-card basket-<%=basket.id%> d-none" >
                      <h2><%= order.id %></h2>
                      <p><%= order.user.email %></p>
                      <p><%= order.price %></p>
                      <p><strong><%= order.status.capitalize %></strong></p>
                      <% if order.status.downcase == 'requested' && (basket.status.downcase =='available' || basket.status.downcase =='reserved') %>
                        <%= link_to "accept", accept_order_path(order) %>
                        <%= link_to "decline", decline_order_path(order) %>
                      <%elsif order.status.downcase == 'confirmed' %>
                        <%= link_to "cancel", cancel_order_path(order)%>
                      <%  end  %>
                  </div>
                <% end %>
             </div>
          </div>
        </div>
      <% end  %>
    </div>
  <% end  %>
  </div>
<% end %>

</div>

app/views/orders/new.html.erb
<%= simple_form_for [@basket, @order] do |f| %>
  <%= f.submit %>
<%  end  %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @basket, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='d-flex justify-content-between align-items-center navbar'>
  <%= link_to root_path,class: 'navbar__item', :action => 'go' do %>
    <h3 class='navbar__item'>GREEN<i class='fas fa-leaf'></i>BASKET</h3>
  <% end%>
  <div class='d-flex justify-content-end'>
    <% if user_signed_in? %>
      <% if current_user.restaurant? %>
        <%= link_to baskets_path,class: 'navbar__item', :action => 'go' do %>
          <i class='fas fa-shopping-basket navbar__icon align-self-center text-center'></i>
        <% end%>
        <%= link_to orders_path,class: 'navbar__item', :action => 'go' do %>
          <i class='fas fa-inbox navbar__icon align-self-center text-center'></i>
        <% end%>
        <%= link_to new_basket_path,class: 'navbar__item', :action => 'go' do %>
          <i class='fas fa-plus navbar__icon align-self-center text-center'></i>
        <% end%>
        <%= link_to destroy_user_session_path, class: 'navbar__item', :method => 'delete' do %>
          <i class='fas fa-sign-out-alt align-self-center text-center'></i>
        <% end%>
        <% else %>
        <%= link_to baskets_path,class: 'navbar__item', :action => 'go' do %>
          <i class='fas fa-shopping-basket navbar__icon align-self-center text-center'></i>
        <% end%>
        <%= link_to orders_path,class: 'navbar__item', :action => 'go' do %>
          <i class='fas fa-inbox navbar__icon align-self-center text-center'></i>
        <% end%>
        <%= link_to favourites_path,class: 'navbar__item', :action => 'go' do %>
          <i class='fas fa-heart navbar__icon align-self-center text-center'></i>
        <% end%>
        <%= link_to destroy_user_session_path, class: 'navbar__item', :method => 'delete' do %>
          <i class='fas fa-sign-out-alt navbar__icon align-self-center text-center'></i>
        <% end%>
      <% end  %>
    <% else %>
      <%= link_to baskets_path,class: 'navbar__item', :action => 'go' do %>
        <i class='fas fa-shopping-basket navbar__icon align-self-center text-center'></i>
      <% end%>
      <%= link_to new_user_session_path,class: 'navbar__item', :action => 'go' do %>
        <i class='fas fa-user navbar__icon align-self-center text-center'></i>
      <% end%>
    <% end %>
  </div>
</nav>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#">About</a>
  <a href="#">Services</a>
  <a href="#">Clients</a>
  <a href="#">Contact</a>
</div>

<script>
  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginRight = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
  }

  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginRight= "0";
    document.body.style.backgroundColor = "white";
  }
</script>